name: Test Suite

'on':
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check code formatting
      run: make check-format

    - name: Compile
      run: make

    - name: Install valgrind
      run: sudo apt-get install -y valgrind

    - name: Check for leaks
      run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./aoc

    - name: Run tests
      run: make test
